### ISSUE TITLE
Me ajude por favor

### ISSUE THREAD

**Issue by RodrigoMaciel13** [RicardoGuariento/MIUI-XML-11-BRAZILIAN#10]
Alterei a menor largura do meu mi 8 lite e ele travou na tela de recovery, sempre mudei a largura na miui 10 e nunca tive problemas, porém na primeira tentativa com a miui 11 isso aconteceu. Quando escolho a opção reboot to system o aparelho reinicia e volta pra a mesma tela de recovery (loop ifinito) o que faço? já tentei conectar via USB com a mi pc suite porém não reconhece o dispositivo, como se eu não tivesse conectado a nenhum suporte. ( me ajude por favor não sei o que fazer)

**Comment by RicardoGuariento** [comment]
Oi Rodrigo, bom dia!

Acredito que mudar o DPI (menor largura) lá nas Opções de Desenvolvedor não tenha relação com esse "bootloop".
Eu sempre fiz isso tanto na MIUI 10 quanto na MIUI 11 (Stock Global e Xioami.eu) e nunca tive problemas.
O que eu sugiro, é você passar a ROM original novamente do zero e depois instalar a ROM Xiaomi.eu novamente.
O PC está reconhecendo o aparelho quando conectado em Fastboot?

**Comment by RodrigoMaciel13** [comment]
Olá Bom dia! obrigado pela resposta, quando conecto em Fastboot o PC reconhece, porém no Mi Suite PC aparece a mensagem "Try connect in normal mode first then switch". Eu sempre alterei até 1000 Dpi na miui 10 e sempre foi tranquilo, porém assim que eu alterei com a miui 11 ficou um simbolo de carregamento com a tela preta uns 5 minutos e depois entrou em brick. Será que a única alternativa vai ser passar a ROM por EDL? meu bootloader é bloqueado sou usuário "comum"

**Comment by RicardoGuariento** [comment]
Conseguiu resolver o problema, amigo?

**Comment by RodrigoMaciel13** [comment]
Olá! consegui resolver sim amigo, instalei a room via EDL no processador, fiz o login na mi conta e consegui acessar o celular. Obrigado pela ajuda! Abraços

Em 28 de nov de 2019 13:17, Ricardo Guariento <notifications@github.com> escreveu:

Conseguiu resolver o problema, amigo?
