### ISSUE TITLE
Tradução PT-BR

### ISSUE THREAD

**Issue by joaopr02** [RicardoGuariento/MIUI-XML-11-BRAZILIAN#11]
Olá.

1 - Nas informações da versão da MIUI 11.0.4.0(Redmi 6 Pro) ainda consta a palavra (Stable).

2 - No app Arquivos, no menu aparece "Definições" em PT-BR deveria ser "Configurações".

**Não consegui adicionar a imagem, mas fica em "Configurações>Meu dispositivo>Versão do dispositivo".
Muito obrigado !

**Comment by RicardoGuariento** [comment]
As correções já foram aplicadas, sairá provavelmente na build da semana que vem.
