### ISSUE TITLE
Tradução PT-BR MIUI 11.0.4.0 - Redmi 6 Pro

### ISSUE THREAD

**Issue by joaopr02** [RicardoGuariento/MIUI-XML-11-BRAZILIAN#13]
Olá.

1 - Mi Health>"Card Settings"
2 - Mi Health>"Card Serttings>Weight"
3 - Mi Health>"Card Serttings>Mestruation"
4 - Mi Health>Sono>"You didn´t get enought sleep."
5 - Mi Health>Sono>"Goal: 8 hours" <-
6 - Mi Health>Sono>Menu a direita>"Sleep settings"
7 - Mi Health>Sono>Menu a direita>Sleep settings>"Sleep duration goal", mesma coisa no card de Atividade e Peso, ambos possuem vários termos em inglês.

8 - Configurações- Idiomas e entrada - "Teclado rato e track pad".

Muito obrigado !

**Comment by jutruka** [comment]
Bom dia João,

Ajustado na versão 9.11.28. Por gentileza, testar.

Muito obrigado pela colaboração.

Atte,
