### ISSUE TITLE
Correções de tradução PT-BR

### ISSUE THREAD

**Issue by joaopr02** [RicardoGuariento/MIUI-XML-11-BRAZILIAN#14]
Olá.

Seguem mais erros encontrados:
1 - Configurações>Tela de bloqueio>"Side panel shortcuts". (Continua em inglês).

2 - Na Galeria, ao marcar mais de 1 foto e pressionar excluir é exibida a janela de confirmação "Extluir X fotos de todos os dispositivos e da Mi Cloud?" > (Palavra "Extluir" ao invés de "Excluir".)

Muito obrigado

**Comment by RicardoGuariento** [comment]
Corrigido!
