### ISSUE TITLE
Tradução

### ISSUE THREAD

**Issue by joaopr02** [RicardoGuariento/MIUI-XML-11-BRAZILIAN#15]
Olá, após a segunda build Estável 11.0.4.0 do Redmi 6 Pro, ainda continuam alguns erros de idioma.

1 - Mi Health>Sono>Menu a direita>"Definições de sono", está em português PT.
2 - A palavra Stable ainda aparece na frente da versão quando abrimos o app Atualizações ex: Instalado Atualmente: MIUI11 | MIUI 11.0.4.0 (Stable).
3 - Wifi - Detalhes da rede wifi - Definições de Proxy(Deveria ser Configurações de proxy) para padronizar.

Obrigado.

**Comment by RicardoGuariento** [comment]
1 - Corrigido
2 - Não tem mais essas linhas no XML, acho que ele tá lendo direto da build.prop
3  - Corrigido
