### ISSUE TITLE
Leitor de impressão digital / zoom modo pinça / Atalho para printar

### ISSUE THREAD

**Issue by bbragas6** [RicardoGuariento/MIUI-XML-11-BRAZILIAN#18]
Boa noite!
Referente ao leitor de biometria consigo cadastrar, porém quando vou desbloquear, não lê, Dá erro até mostrar outras opções de desbloqueio.
O Zoom com pinça e o atalho para printar deslizando os três dedos estão configurados corretamente, porém não consigo usar nenhum dos recursos.

**Comment by RicardoGuariento** [comment]
Amigo, infelizmente não tenho acesso ao desenvolvimento das ROMs, só mantenho as traduções. Neste caso, seria interessante você postar isso lá no fórum da xiaomi.eu
