### ISSUE TITLE
MIUI 11 Tradução BR

### ISSUE THREAD

**Issue by joaopr02** [RicardoGuariento/MIUI-XML-11-BRAZILIAN#19]
Olá, segue mais sugestões:

Mi Video - 3 pontos no canto superior a direita - A palavra "Configurações" está quebrada para a linha de baixo separada pelo "-" se pudesse redimensionar a janela ficaria mais bonita.
Mi Video - Configurações - Notificações "push" - "Ative para receber notificações push" (Seria esse termo mesmo ou seria melhor remover a palavra "push" ?

Obrigado !

**Comment by RicardoGuariento** [comment]
Deixei a palavra "Configurações" como "Config." pois não tenho como editar o tamanho do menu. E removi o "push"
