### ISSUE TITLE
Câmera

### ISSUE THREAD

**Issue by dvd2020** [RicardoGuariento/MIUI-XML-11-BRAZILIAN#20]
A versão 20.2.20 v2 está com incompatibilidade com a câmera stock quando instala o magisk.

**Comment by RicardoGuariento** [comment]
Neste caso, você precisa reportar isso aos desenvolvedores da ROM no forum da xiaomi.eu. Eu não tenho qualquer tipo de envolvimento com eles, apenas traduzo os XML's.

**Comment by dvd2020** [comment]
Ok. Obrigado
