### ISSUE TITLE
Idioma Português brasileiro não disponível

### ISSUE THREAD

**Issue by brunnogama** [RicardoGuariento/MIUI-XML-11-BRAZILIAN#3]
Na atualização 9.9.26, o idioma pt_br não está mais disponível. Mi Mix 2;

**Comment by FuurioBR** [comment]
Mesmo problema aqui no meu Redmi 5 plus...
Ele veio com pt-br selecionado, mas tudo estava em pt-pt, fui nas configurações de idioma e só tinha "português", sendo de Portugal

**Comment by RicardoGuariento** [comment]
> Mesmo problema aqui no meu Redmi 5 plus...
> Ele veio com pt-br selecionado, mas tudo estava em pt-pt, fui nas configurações de idioma e só tinha "português", sendo de Portugal

Eu estou revisando os XMLs de tradução, por isso nessa primeira build da MIUI 11 não subi os XML's, logo a tradução estará disponível.

**Comment by fdp1217** [comment]
Mesma coisa no mi 9t
