### ISSUE TITLE
Sugestões para Miui 11 em Pt-BR (alguns textos ainda estão em Pt-pt)

### ISSUE THREAD

**Issue by danilomazzaro** [RicardoGuariento/MIUI-XML-11-BRAZILIAN#6]
**_"Local":
"Texto atual" -> "Sugestão/Correção_**"

-------------------------------------------------------------
Em configurações:
Ligações e partilha -> Ligações e compartilhamento
-------------------------------------------------------------
Em configurações > Notificações e tela de bloqueio:
Mostrar ecrã -> Exibir na tela
-------------------------------------------------------------
Configurações > Aplicativos:
Aplicativos clones -> Aplicativos clonados
-------------------------------------------------------------

Essas sugestões são baseadas em:
Xiaomi Mi8
Miui 11.0.3 Estável

**Comment by jutruka** [comment]
> **_"Local": "Texto atual" -> "Sugestão/Correção_**"
> 
> ## Em configurações:
> Ligações e partilha -> Ligações e compartilhamento
> ## Em configurações > Notificações e tela de bloqueio:
> Mostrar ecrã -> Exibir na tela
> ## Configurações > Aplicativos:
> Aplicativos clones -> Aplicativos clonados
> Essas sugestões são baseadas em:
> Xiaomi Mi8
> Miui 11.0.3 Estável

**Comment by jutruka** [comment]
Boa tarde Danilo

Correções efetuadas!

Se permanecer alguma coisa, por favor só nos avisar.

Grato pela colaboração!
