### ISSUE TITLE
Dúvida sobre tradução

### ISSUE THREAD

**Issue by joaopr02** [RicardoGuariento/MIUI-XML-11-BRAZILIAN#9]
Olá, poderiam tirar uma dúvida por gentileza ?

Eu tenho feito algumas indicações para correção de tradução da MIUI, mas tenho uma dúvida.

Quando vocês fazem uma correção, é realizado um novo upload do arquivo arquivo de atualização no site ou as mudanças refletirão apenas na próxima atualização ?

Muito obrigado !

**Comment by RicardoGuariento** [comment]
Oi boa tarde,

As traduções saem sempre na próxima atualização que é quando compilam a ROM.

Infelizmente eu me afastei um pouco das traduções por motivos de saúde, mas um outro colaborador está cuidando das traduções.

O e-mail dele é alexjensen.rickli@gmail.com

Se ainda tiver alguma coisa não traduzida, envie um e-mail pra ele com os prints que ele corrige.

Por hora eu tô só ajudando ele.

Abraço

Atenciosamente,

Ricardo Guariento
E-mail: ricardo.guariento@hotmail.com
Cel./WhatsApp: (19) 99556-6190

________________________________

**Comment by joaopr02** [comment]
Caso eu coloque neste site aqui como um ticket, ele também validará/corrigirá correto ?

Obrigado desde já pela resposta !
